Added README.md for the Project
McChronicle/BingeSkipper pull request #5
Opened 2023-05-06 11:58 UTC by Error042

2023-05-06 15:08 UTC, McChronicle requested changes
looks nice, only some smaller suggestions

2023-05-06 15:08 UTC, McChronicle commented on README.md
> +## How to install
maybe put the instructions below under a "install manually" section, as the standard way for installing should probaply be via the browser extension stores
```suggestion
## How to install
### Chromium based browsers
1. Visit the page for this extension [in the chrome web store](https://chrome.google.com/webstore/detail/netflix-autoskip/oglhelhnbhiigifcgohdmhgaodaonhjl)
2. Click "add"
3. Enjoy! Updates will be applied automatically as we publish them on the chrome web store.

### Firefox based browsers
1. Visit the page for this extension [in the firefox addon store](https://addons.mozilla.org/de/firefox/addon/netflix-autoskip/)
2. Click "add to firefox"
3. Enjoy! Updates will be applied automatically as we publish them on the firefox addon store.

### Manual installation
```

2023-05-06 15:08 UTC, McChronicle commented on README.md
> +- The "Continue Watching" button
this extension doesn't skip the "who's watching" screen, but it auto clicks "next episode"
```suggestion
This is a simple plugin for Chromium based and Firefox based browsers that skips the following Netflix screens:

- The "Skip Intro" button
- The "Continue Watching" button
- The "Next Episode" button (credits)
```

2023-05-07 16:12 UTC, Error042 commented
@McChronicle I updated the file by your suggestions

2023-05-07 19:42 UTC, McChronicle approved these changes

2023-05-07 19:43 UTC, merged